config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'chatroom/index'
  post 'message', to: 'messages#create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "chatroom#index"

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  def index
    if user_signed_in?
      @message = Message.new
      @messages = Message.custom_display
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel",
                                    {mod_message: message_render(message)}
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: {message: message})
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned mdedium icon header">
<i class="circular rocketchat blue icon"></i>
Message Me!
</h4>

<div class="ui two column grid">
<div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
    <div class="content" id="messages">      
        <div class="ui feed" id="message-container">
          <%= render @messages %>
        </div>
    </div>
    <div class="extra content">
        <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body %>
              <%= f.button '<i class="bordered inverted blue edit icon"></i>'.html_safe %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
</div>

<div class="four wide column">
<div class="ui fluid raised card chatbox">
    <div class="content">
    <div class="ui inverted vertical menu">
        <a class="item">  
        Home
        </a>
        <a class="item">  
        Message
        </a>
        <a class="item">  
        Friends
        </a>
    </div>
    </div>
</div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navigation" %>
    <div class="ui container">
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.email %></em>:<%= message.body %>
    </div>
  </div>
</div>

app/views/shared/_navigation.html.erb
<div class="ui inverted small menu">
  <div class="ui container">  
    <a class="item">
      Chatroom
    </a>
    <a class="item">
      Messages
    </a>
    <div class="right menu">
      <% if user_signed_in? %>
        <div class="ui dropdown item">
          Account <i class="dropdown icon"></i>
          <div class="menu">
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "item" %>
          </div>
        </div>
      <% else %>
        <%= link_to "Log In", new_user_session_path, class: "item" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "item" %>
      <% end %>
    </div>
  </div>
</div>